version: '3.9'

services:
  djangoapp:
    container_name: djangoapp
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./djangoapp:/djangoapp
      - ./scripts:/scripts
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    working_dir: /djangoapp
    depends_on:
      psql:
        condition: service_healthy
    restart: unless-stopped
    networks:  
      - app_network

  psql:
    container_name: psql
    image: postgres:14-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blog_user -d blog_base_de_dados"]
      start_period: 30s  
      interval: 10s
      timeout: 5s
      retries: 6
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    networks: 
      - app_network

networks:  
  app_network:
    driver: bridge